### ISSUE TITLE
Make NuGet package Strongly Named

### ISSUE THREAD

**Issue by MarkCurtis-2** [amingolmahalle/HttpClientToCurlGenerator#40] opened 2024-04-03 13:37 UTC
When building my project I get the following warning:
Severity	Code	Description	
Warning	CS8002	Referenced assembly 'HttpClientToCurl, Version=2.0.6.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.	

Can you make NuGet package strongly named to avoid this?

**Comment by amingolmahalle** [comment] 2024-04-03 15:35
Thanks, dear @MarkCurtis-2
I will check it.

**Comment by amingolmahalle** [comment] 2024-04-04 09:44
@MarkCurtis-2 do you have an idea?

**Comment by naeemaei** [comment] 2024-06-10 15:33
Considering that a lot of time has passed since the registration of this issue and we have not found enough details to reproduce this problem, we are closing this issue.
If you would like, create a new issue with more details about this problem.

**Closed by naeemaei** 2024-06-10 15:33 UTC
Labels: help wanted
